[package]
name = "pyegraphsgood"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyegraphsgood"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
egg = "^0.9"
